// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Non-null assertion because DATABASE_URL must be defined at runtime
    url: process.env["DATABASE_URL"] as string,
  },
  // Note: Seed configuration is in package.json, not here (Prisma 6)
});
